version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase
  build:
    commands:
      - echo Build started on `date`
      # Ensure the build command is correct and exists in package.json
      - if [ -f package.json ] && grep -q '"build"' package.json; then npm run build; else echo "No build script found in package.json"; fi
  post_build:
    commands:
      - echo Build completed on `date`
      # Ensure the test command is correct and exists in package.json
      - if [ -f package.json ] && grep -q '"test"' package.json; then npm run test; else echo "No test script found in package.json"; fi || true

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'